name: Test Augment Agent Action

on:
  workflow_dispatch:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Augment Agent
        uses: ./
        with:
          augment_session_auth: ${{ secrets.AUGMENT_SESSION_AUTH }}
          instruction: "Say hello"
